# Generated by Django 5.2 on 2025-04-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='applicationtype',
            options={'verbose_name': 'Application Type', 'verbose_name_plural': 'Application Type'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='award',
            options={'verbose_name': 'Award', 'verbose_name_plural': 'Awards'},
        ),
        migrations.AlterModelOptions(
            name='awardwinner',
            options={'verbose_name': 'Award Winner', 'verbose_name_plural': 'Award Winners'},
        ),
        migrations.AlterModelOptions(
            name='basemodel',
            options={'verbose_name': 'Base Model', 'verbose_name_plural': 'Base Models'},
        ),
        migrations.AlterModelOptions(
            name='feat',
            options={'verbose_name': 'Feat', 'verbose_name_plural': 'Feats'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='projectprogress',
            options={'verbose_name': 'Project Progress', 'verbose_name_plural': 'Project Progress'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'AReviews'},
        ),
        migrations.AlterModelOptions(
            name='seoanalytic',
            options={'verbose_name': 'SEO Analytic', 'verbose_name_plural': 'SEO Analytics'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Specialization', 'verbose_name_plural': 'Specializations'},
        ),
        migrations.AlterModelOptions(
            name='websiteservice',
            options={'verbose_name': 'Web Site Service', 'verbose_name_plural': 'Web Site Services'},
        ),
    ]
