# Generated by Django 5.2 on 2025-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_basemodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
